version: "3.8"

networks:
    backend:
      driver: ${NETWORKS_DRIVER}

volumes:
    mongo:
      driver: ${VOLUMES_DRIVER}

services:

### MongoDB  #############################################
  mongo:
    build: ./docker/mongo
    ports:
      - "${MONGODB_PORT}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - ${DATA_PATH_HOST}/mongo:/data/db
      - ${DATA_PATH_HOST}/mongo_config:/data/configdb
    networks:
      - backend